// Shared Premium plan definitions used across onboarding and premium screens
// Shared Premium plan definitions used across onboarding and premium screens
export const PLANS = [
  {
    id: "BASIC",
    name: "Basic",
    tagline: "Free plan to get started",
    price: "₦0",
    period: "/month",
    color: "#6b7280",
    gradientFrom: "#9ca3af",
    gradientTo: "#4b5563",
    icon: "leaf",
    badge: "Free" as string | null,
    features: [
      "Up to 15 records per field",
      "Basic HR management",
      "Chat & messaging",
      "Standard support",
    ],
    missing: ["Advanced analytics", "Priority support", "Custom branding", "Multi-branch management"],
  },
  {
    id: "PREMIUM",
    name: "Premium",
    tagline: "Best for growing teams",
    price: "₦5,000",
    period: "/month",
    color: "#6366f1",
    gradientFrom: "#6366f1",
    gradientTo: "#8b5cf6",
    icon: "crown",
    badge: "Popular" as string | null,
    features: [
      "Up to 50 records per field",
      "Advanced HR & Payroll",
      "Finance & budget tracking",
      "Priority support",
    ],
    missing: ["Custom branding", "Multi-branch management"],
  },
  {
    id: "PRO",
    name: "Pro",
    tagline: "Built for scaling businesses",
    price: "₦10,000",
    period: "/month",
    color: "#f59e0b",
    gradientFrom: "#f59e0b",
    gradientTo: "#d97706",
    icon: "gem",
    badge: "Professional" as string | null,
    features: [
      "Up to 100 records per field",
      "Full HR & payroll suite",
      "Advanced analytics",
      "Multi-branch management",
      "Priority support 24/7",
    ],
    missing: ["Custom branding"],
  },
  {
    id: "PRO_YEARLY",
    name: "Yearly Plan",
    tagline: "Unlimited scale & maximum value",
    price: "₦90,000",
    period: "/year",
    color: "#10b981",
    gradientFrom: "#10b981",
    gradientTo: "#059669",
    icon: "building",
    badge: "Best Value (Save 25%)" as string | null,
    features: [
      "Unlimited records",
      "Everything in Pro",
      "Custom branding & domain",
      "Dedicated account manager",
      "SLA guarantee",
      "API access",
    ],
    missing: [],
  },
];

