// Shared Premium plan definitions used across onboarding and premium screens
export const PLANS = [
  {
    id: "starter",
    name: "Starter",
    tagline: "Perfect for small teams",
    price: "$19",
    period: "/month",
    color: "#6366f1",
    gradientFrom: "#6366f1",
    gradientTo: "#8b5cf6",
    icon: "bolt-lightning",
    badge: null as string | null,
    features: [
      "Up to 10 employees",
      "Basic HR management",
      "Chat & messaging",
      "Monthly payroll reports",
      "Email support",
    ],
    missing: ["Advanced analytics", "Priority support", "Custom branding"],
  },
  {
    id: "pro",
    name: "Pro",
    tagline: "Built for growing businesses",
    price: "$49",
    period: "/month",
    color: "#f59e0b",
    gradientFrom: "#f59e0b",
    gradientTo: "#d97706",
    icon: "crown",
    badge: "Most Popular" as string | null,
    features: [
      "Up to 100 employees",
      "Full HR & payroll suite",
      "Advanced analytics",
      "Finance & budget tracking",
      "Priority support",
      "Multi-branch management",
    ],
    missing: ["Custom branding"],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    tagline: "Unlimited scale for large orgs",
    price: "$129",
    period: "/month",
    color: "#10b981",
    gradientFrom: "#10b981",
    gradientTo: "#059669",
    icon: "building",
    badge: "Best Value" as string | null,
    features: [
      "Unlimited employees",
      "Custom branding & domain",
      "Dedicated account manager",
      "SLA guarantee",
      "API access",
      "Advanced security controls",
      "24/7 priority support",
    ],
    missing: [],
  },
];
