services:
  - type: web
    name: adminsuite-api
    runtime: python
    rootDir: admin-suite-backend
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.whjxjqsxrnjpkoknfixo:AdminSuite2210@aws-0-eu-west-1.pooler.supabase.com:6543/postgres
      - key: DJANGO_ALLOWED_HOSTS
        fromService:
          type: web
          name: adminsuite-api
          property: host
      - key: CORS_ALLOWED_ORIGINS
        value: https://adminsuite.onrender.com,https://adminsuite-web.onrender.com
      - key: CLOUDINARY_URL
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@adminsuite.app
      - key: ADMIN_PASSWORD
        value: "AdminSuite#2210"
      - key: SETUP_SECRET_TOKEN
        value: adminsuite-setup-9x7k2p

  - type: web
    name: adminsuite
    runtime: static
    rootDir: admin-suite-landing
    buildCommand: npm run build
    staticPublishPath: dist

  - type: web
    name: adminsuite-web
    runtime: static
    rootDir: admin-suite-web
    buildCommand: npm run build
    staticPublishPath: dist

