# Generated by Django 6.0.4 on 2026-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_budgetcategory_user_client_user_debt_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_owes_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='client',
            name='company_owes_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='client',
            name='lifetime_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='client',
            name='pending_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
