# Generated by Django 6.0.5 on 2026-05-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emailotp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailOTP',
            new_name='EmailVerificationCode',
        ),
    ]
