# Generated by Django 6.0.5 on 2026-05-23 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_emailotp_emailverificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('heard_from', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('friend', 'Friend'), ('others', 'Others')], default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_avatars/')),
                ('bio', models.TextField(blank=True, default='')),
                ('social_link', models.URLField(blank=True, default='')),
                ('profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
