# Generated by Django 6.0.5 on 2026-06-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_employee_flag_note_employee_flag_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemessage',
            name='delivery_mode',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='both', max_length=20),
        ),
    ]
