# Generated by Django 6.0.6 on 2026-06-10 21:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_chat_settings'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human‑readable organization name.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User (usually a CEO) that created the organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch name (unique within its organization).', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='User who created the branch (usually a CEO or branch admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Parent organization.', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('BASIC', 'Basic – Free'), ('PREMIUM', 'Premium – $25/mo'), ('PRO', 'Pro – $45/mo')], default='BASIC', help_text='Current subscription tier.', max_length=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_records_per_field', models.PositiveIntegerField(default=15, help_text='Maximum records allowed per field for this plan.', validators=[django.core.validators.MinValueValidator(1)])),
                ('features', models.JSONField(blank=True, default=dict, help_text="Feature toggles (e.g., {'ai_automation': True}).")),
                ('organization', models.OneToOneField(help_text='Each organization has exactly one active subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('user', models.OneToOneField(help_text='Link to the Django auth user.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extension', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('BRANCH_ADMIN', 'Branch Administrator'), ('MANAGER', 'Manager'), ('HR', 'Human Resources'), ('ASSISTANT_ADMIN', 'Assistant Administrator')], default='MANAGER', help_text='Role within the organization/branch.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch the user manages (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_members', to='api.branch')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization the user belongs to (null for branch‑only admins).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.organization')),
            ],
        ),
    ]
