# Generated by Django 6.0.6 on 2026-06-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_chatmessage_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsettings',
            name='allow_employee_private_chat',
            field=models.BooleanField(default=False),
        ),
    ]
