# Generated by Django 6.0.6 on 2026-06-14 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='api.branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.branch'),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves', to='api.branch'),
        ),
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.branch'),
        ),
        migrations.AddField(
            model_name='savings',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_plans', to='api.branch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.branch'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='role',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('BRANCH_ADMIN', 'Branch Administrator'), ('HR', 'HR Manager'), ('FINANCE', 'Finance Officer'), ('OPERATIONS', 'Operations Manager'), ('SECRETARY', 'Secretary'), ('DEPT_MANAGER', 'Department Manager'), ('EMPLOYEE', 'Employee')], default='MANAGER', help_text='Role within the organization/branch.', max_length=20),
        ),
    ]
