# Generated by Django 6.0.6 on 2026-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_budgetcategory_branch_employee_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Physical location/address of the branch.', max_length=255),
        ),
    ]
