# Generated by Django 6.0.6 on 2026-06-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_branch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefinance',
            name='last_finance_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
