# Generated by Django 6.0.6 on 2026-06-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_employeefinance_last_finance_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('BASIC', 'Basic – Free'), ('PREMIUM', 'Premium – $25/mo'), ('PRO', 'Pro – $45/mo'), ('PRO_YEARLY', 'Pro Yearly – $399/yr')], default='BASIC', help_text='Current subscription tier.', max_length=10),
        ),
    ]
