# Generated by Django 5.0.14 on 2026-10-01 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_chatmessage_delivery_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam / Scam / Advertising'), ('harassment', 'Harassment or Bullying'), ('inappropriate_content', 'Inappropriate or Explicit Content'), ('hate_speech', 'Hate Speech or Discrimination'), ('impersonation', 'Impersonation or Fake Account'), ('policy_violation', 'Company / Community Policy Violation'), ('other', 'Other Reason')], default='other', max_length=40)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved (Action Taken)'), ('dismissed', 'Dismissed (No Violation)')], default='pending', max_length=20)),
                ('action_taken', models.CharField(choices=[('none', 'No Action Taken'), ('warned', 'User Warned'), ('chat_blocked', 'Blocked from Chat'), ('suspended', 'Account Suspended (is_active=False)'), ('deleted', 'Account Deleted')], default='none', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.chatmessage')),
                ('company_user', models.ForeignKey(blank=True, help_text='Workspace admin context', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_reported_accounts', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reported Account',
                'verbose_name_plural': 'Reported Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('chat_group', 'Group Chat Block'), ('direct_message', 'Direct Message Block'), ('workspace', 'Workspace Wide Block')], default='chat_group', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_issued', to=settings.AUTH_USER_MODEL)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('company_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_blocked_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked Account',
                'verbose_name_plural': 'Blocked Accounts',
                'ordering': ['-created_at'],
                'unique_together': {('blocked_by', 'blocked_user', 'scope')},
            },
        ),
    ]
